### ISSUE TITLE
No overload and cast for this element

### ISSUE THREAD

**Issue by CrisMon-01** [ajsmithsw/PlacesSearchBar#3] opened 2018-02-21 08:53 UTC
Hi, i ave a problem with this project, i have use it for an element, thank you for the work,
but in the class i had to use i have a probem with this 2 elements

`            search_bar.Type = PlaceType.Cities;  `
`            search_bar.PlacesRetrieved += Search_Bar_PlacesRetrieved;`

on the .cs class
for the first xamarin want a cast but there is no one,
for the second it say there is no overload to PlacesRetrievedEventHandler
@ajsmithsw

**Comment by ajsmithsw** [comment] 2018-02-21 09:12
@CrisMon-01 , What does your Search_Bar_PlacesRetrieved() look like? It should take arguments like this:
```void PlacesRetrievedEventHandler(object sender, AutoCompleteResult result);```

If you have a full stack trace, paste it here as it will help

**Comment by CrisMon-01** [comment] 2018-02-21 12:49
This is the page i working on, and i haven't this snippet you tell,
i have this bar on a new item page with other field etc 

`using System;
using System.Collections.Generic;
using Xamarin.Forms;
using System.Collections.ObjectModel;
using Xamarin.Forms.Maps;
using Firebase.Xamarin.Database;
using Firebase.Xamarin.Database.Query;
using System.ComponentModel;
using System.Threading.Tasks;
using Xamarin.Forms.Xaml;
using DurianCode.PlacesSearchBar;
//Xam.Plugin.Geolocator
//DurianCode.PlacesSearchBar

namespace Sport
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class NewItemPage : ContentPage
    {
        string GooglePlacesApiKey = "I put a test string for the snippet";

        public Item Item { get; set; }

        public NewItemPage()
        {
            InitializeComponent();
            BindingContext = Item = new Item();

            //SERACHTAB
            search_bar.ApiKey = GooglePlacesApiKey;
            search_bar.Type = PlaceType.Cities;     
            search_bar.PlacesRetrieved += Search_Bar_PlacesRetrieved;
            search_bar.TextChanged += Search_Bar_TextChanged;
            search_bar.MinimumSearchText = 2;
            results_list.ItemSelected += Results_List_ItemSelected;

            var map = new Map(
            MapSpan.FromCenterAndRadius(new Position(37, -122), Distance.FromMiles(0.3)))
            {
                IsShowingUser = true,
                HeightRequest = 100,
                WidthRequest = 960,
                VerticalOptions = LayoutOptions.FillAndExpand
            };
            var slider = new Slider(1, 18, 1);
            slider.ValueChanged += (sender, e) =>
            {
                var zoomLevel = e.NewValue; // between 1 and 18
                var latlongdegrees = 360 / (Math.Pow(2, zoomLevel));
                map.MoveToRegion(new MapSpan(map.VisibleRegion.Center, latlongdegrees, latlongdegrees));
            };
        }
        //metodi

        void Search_Bar_PlacesRetrieved(object sender, AutoCompleteResult result)
        {
            results_list.ItemsSource = result.AutoCompletePlaces;
            spinner.IsRunning = false;
            spinner.IsVisible = false;

            if (result.AutoCompletePlaces != null && result.AutoCompletePlaces.Count > 0)
                results_list.IsVisible = true;
        }

        void Search_Bar_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (!string.IsNullOrEmpty(e.NewTextValue))
            {
                results_list.IsVisible = false;
                spinner.IsVisible = true;
                spinner.IsRunning = true;
            }
            else
            {
                results_list.IsVisible = true;
                spinner.IsRunning = false;
                spinner.IsVisible = false;
            }
        }

        async void Results_List_ItemSelected(object sender, SelectedItemChangedEventArgs e)
        {
            if (e.SelectedItem == null)
                return;

            var prediction = (AutoCompletePrediction)e.SelectedItem;
            results_list.SelectedItem = null;

            var place = await Places.GetPlace(prediction.Place_ID, GooglePlacesApiKey);

            if (place != null)
                await DisplayAlert(
                    place.Name, string.Format("Lat: {0}\nLon: {1}", place.Latitude, place.Longitude), "OK");
        }

        async void Save_Clicked(object sender, EventArgs e)
        {
            if (Item.Title == null || Item.Title.Equals("") || Item.Date == null)
            {
                await DisplayAlert("Error", "You must insert a title and a date for your event", "Ok");
            }
            else
            {
                /*await App.Database.SaveItemAsync(Item);
                //MessagingCenter.Send(this, "AddItem", Item);

                await firebase.Child("User1").Child(Item.Id.ToString()).PutAsync(Item);*/
                //await manager.SaveTaskAsync(Item);
                await DatabaseManager.DefaultManager.SaveTaskAsync(Item);
                await DisplayAlert("Item saved", "You saved the item " + Item.Title, "Ok");
                await Navigation.PopToRootAsync();
            }
        }
        async void Choose_date(object sender, EventArgs e)
        {
            await Navigation.PushModalAsync(new Pagine.CalendarPage(Item, DataCamp));
        }

        public void Switch_toggled()
        {
            if (Swi.IsToggled)
            {
                TipoPost.Text = "Public";
                Item.IsPublic = true;
            }
                
            else
            {
                TipoPost.Text = "Private";
                Item.IsPublic = false;
            }
        }

        private void Picker_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName.Equals("Time"))
                Item.Time = Picker.Time.ToString();
        }

    }
}

`

@ajsmithsw

**Comment by ajsmithsw** [comment] 2018-02-21 13:03
I think I know what the problem is. Are you using the NuGet package, or did you copy the project from this repo?

If it's the latter, check that you have made a reference to the project in your core project

**Comment by CrisMon-01** [comment] 2018-02-21 13:59
I have copy paste the code but i have install the nuget pachage, yesterday i had same problem with the assembly reference but i have fix it with the reinstall of the nuget

**Comment by ajsmithsw** [comment] 2018-02-21 14:04
OK, so this sounds like it was a compilation issue then caused by an incorrect package reference. I'll close this issue.

**Closed as completed by ajsmithsw** 2018-02-21 14:04 UTC
